// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skillsets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cf9c3d2-e868-45fc-b20e-551c0a7d60f2"),
                            Hobby = "Gaming",
                            Mail = "john.doe@gmail.com",
                            PhoneNumber = "0112345678",
                            Skillsets = "C#, ASP.NET, EF Core",
                            Username = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("d4068753-8e00-495d-8c61-82dc5206c4fe"),
                            Hobby = "Reading",
                            Mail = "jane.smith@gmail.com",
                            PhoneNumber = "0123456789",
                            Skillsets = "JavaScript, React, Node.js",
                            Username = "Jane Smith"
                        },
                        new
                        {
                            Id = new Guid("12e994d5-b6dc-4f3e-80a0-8781577749a2"),
                            Hobby = "Cycling",
                            Mail = "michael.johnson@gmail.com",
                            PhoneNumber = "0134567890",
                            Skillsets = "Python, Django, Flask",
                            Username = "Michael Johnson"
                        },
                        new
                        {
                            Id = new Guid("c07d6737-993c-4963-a6c4-895e4a2cd62e"),
                            Hobby = "Photography",
                            Mail = "emily.davis@gmail.com",
                            PhoneNumber = "0145678901",
                            Skillsets = "Java, Spring Boot",
                            Username = "Emily Davis"
                        },
                        new
                        {
                            Id = new Guid("e5469a76-e9d5-4815-97a3-e12c7c087aca"),
                            Hobby = "Cooking",
                            Mail = "daniel.wilson@gmail.com",
                            PhoneNumber = "0156789012",
                            Skillsets = "Go, Kubernetes, Docker",
                            Username = "Daniel Wilson"
                        },
                        new
                        {
                            Id = new Guid("70381b5f-e909-4f3e-b8cb-870d13d01773"),
                            Hobby = "Hiking",
                            Mail = "olivia.brown@gmail.com",
                            PhoneNumber = "0167890123",
                            Skillsets = "Ruby, Rails, PostgreSQL",
                            Username = "Olivia Brown"
                        },
                        new
                        {
                            Id = new Guid("1c3fb62d-d897-4516-ba10-5374bb2556a5"),
                            Hobby = "3D Modeling",
                            Mail = "william.lee@gmail.com",
                            PhoneNumber = "0178901234",
                            Skillsets = "C++, Unreal Engine",
                            Username = "William Lee"
                        },
                        new
                        {
                            Id = new Guid("0ec1ebdb-5d63-4594-8d8e-ccb5c5005ad4"),
                            Hobby = "Traveling",
                            Mail = "sophia.martin@gmail.com",
                            PhoneNumber = "0189012345",
                            Skillsets = "Swift, iOS Development",
                            Username = "Sophia Martin"
                        },
                        new
                        {
                            Id = new Guid("bfe1daf4-a6f3-43fc-baef-9afd26f033bd"),
                            Hobby = "Fishing",
                            Mail = "james.taylor@gmail.com",
                            PhoneNumber = "0190123456",
                            Skillsets = "PHP, Laravel, MySQL",
                            Username = "James Taylor"
                        },
                        new
                        {
                            Id = new Guid("11ea1418-266c-416c-b2f8-74e03cf13f91"),
                            Hobby = "Painting",
                            Mail = "ava.anderson@gmail.com",
                            PhoneNumber = "0111234567",
                            Skillsets = "HTML, CSS, UX Design",
                            Username = "Ava Anderson"
                        },
                        new
                        {
                            Id = new Guid("664244ba-adaa-4a11-aaa6-11b5b7339934"),
                            Hobby = "Chess",
                            Mail = "benjamin.thomas@gmail.com",
                            PhoneNumber = "0122345678",
                            Skillsets = "Python, Pandas, NumPy",
                            Username = "Benjamin Thomas"
                        },
                        new
                        {
                            Id = new Guid("ad361799-b933-4645-ac1e-862662323818"),
                            Hobby = "Writing",
                            Mail = "mia.jackson@gmail.com",
                            PhoneNumber = "0133456789",
                            Skillsets = "R, Data Analysis",
                            Username = "Mia Jackson"
                        },
                        new
                        {
                            Id = new Guid("b4971baa-da7f-4e97-b80b-97e8ed7d01bf"),
                            Hobby = "Skiing",
                            Mail = "logan.white@gmail.com",
                            PhoneNumber = "0144567890",
                            Skillsets = "Scala, Akka, Kafka",
                            Username = "Logan White"
                        },
                        new
                        {
                            Id = new Guid("9f89b5c7-88ee-411d-99f1-b26e2c085c4f"),
                            Hobby = "Drawing",
                            Mail = "isabella.harris@gmail.com",
                            PhoneNumber = "0155678901",
                            Skillsets = "Android, Kotlin, Jetpack",
                            Username = "Isabella Harris"
                        },
                        new
                        {
                            Id = new Guid("b0517b81-9e6c-4854-b5dc-6b68511f49dd"),
                            Hobby = "Board Games",
                            Mail = "ethan.lewis@gmail.com",
                            PhoneNumber = "0166789012",
                            Skillsets = "Unity, Game Dev, C#",
                            Username = "Ethan Lewis"
                        },
                        new
                        {
                            Id = new Guid("0934de1b-0147-4acc-90e5-4b26789595ef"),
                            Hobby = "Singing",
                            Mail = "charlotte.clark@gmail.com",
                            PhoneNumber = "0177890123",
                            Skillsets = "Figma, UI Design",
                            Username = "Charlotte Clark"
                        },
                        new
                        {
                            Id = new Guid("6baf8e1c-84e9-4a2f-a3b3-bce5ebee2d10"),
                            Hobby = "Running",
                            Mail = "alexander.young@gmail.com",
                            PhoneNumber = "0188901234",
                            Skillsets = "Machine Learning, TensorFlow",
                            Username = "Alexander Young"
                        },
                        new
                        {
                            Id = new Guid("433a1995-f666-420f-aba3-a1dce486d12f"),
                            Hobby = "Yoga",
                            Mail = "amelia.king@gmail.com",
                            PhoneNumber = "0199012345",
                            Skillsets = "SQL, ETL, Data Warehousing",
                            Username = "Amelia King"
                        },
                        new
                        {
                            Id = new Guid("9c18f628-def7-49a8-93a3-808516c6052c"),
                            Hobby = "Trekking",
                            Mail = "henry.scott@gmail.com",
                            PhoneNumber = "0110123456",
                            Skillsets = "Bash, Linux, Ansible",
                            Username = "Henry Scott"
                        },
                        new
                        {
                            Id = new Guid("3a3a69b1-8c50-4d14-b7de-b555e4f94057"),
                            Hobby = "Origami",
                            Mail = "evelyn.green@gmail.com",
                            PhoneNumber = "0121234567",
                            Skillsets = "AI, LLMs, OpenAI API",
                            Username = "Evelyn Green"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
